# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'dotenv-rails' # , groups: [:development, :test]
gem 'json'
gem 'nokogiri'
gem 'open-uri'
gem 'puma'
gem 'rubocop'
gem 'sinatra'

group :test, :development do
  gem 'pry'
  gem 'pry-nav'
  gem 'pry-remote'
  gem 'rack-test'
  gem 'rspec'
end

gem 'sinatra-cross_origin', '~> 0.3.1'
