# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "nokogiri"
gem "open-uri"
gem 'sinatra'
gem 'json'
gem 'dotenv-rails' #, groups: [:development, :test]
gem 'puma'

group :test, :development do
  gem "rspec"
  gem "rack-test"
  gem 'pry'
  gem 'pry-remote'
  gem 'pry-nav'
end

gem "sinatra-cross_origin", "~> 0.3.1"
